### ISSUE TITLE
Recoverable fatal error: Object of class PhpParser\Node\Expr\Variable could not be converted to string

### ISSUE THREAD

**Issue by jurgenhaas** [palantirnet/drupal-rector#92] opened 2020-05-22 13:27 UTC
After having processed 20 projects successfully today, I run across the project https://www.drupal.org/project/sane which throws the following exception:

```
Rector 0.8.x-dev@8896f0a
Config file: rector.yml

  66/126 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  52%

Recoverable fatal error: Object of class PhpParser\Node\Expr\Variable could not be converted to string in /var/www/html/vendor/palantirnet/drupal-rector/src/Rector/Deprecation/EntityManagerRector.php on line 65

```

I was trying to xdebug that code by inserting this code before line 61:

```
        try {
            if ($node->name instanceof Node\Identifier) {
                $a1 = (string) $node->class;
                $a2 = (string) $node->name;
            }
        }
        catch (\Exception $ex) {
            $x = 1;
        }
```

It then throws the exception for `(string) $node->class;` but doesn't catch it and just quits. So I can't tell the status of $node at the time.

The stack trace in sdebug mode is like this:

```
Recoverable fatal error: Object of class PhpParser\Node\Expr\Variable could not be converted to string in /var/www/html/vendor/palantirnet/drupal-rector/src/Rector/Deprecation/EntityManagerRector.php on line 65

Call Stack:
    0.0056     396960   1. {main}() /var/www/html/vendor/rector/rector-prefixed/rector:0
    0.1133    6036120   2. require('phar:///var/www/html/vendor/rector/rector-prefixed/rector/bin/rector') /var/www/html/vendor/rector/rector-prefixed/rector:6
   20.3751   44351384   3. Rector\Core\Console\Application->run(???, ???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/bin/rector:46
   20.3764   44355616   4. Rector\Core\Console\Application->doRun(???, ???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/vendor/symfony/console/Application.php:136
   20.3787   44445560   5. Rector\Core\Console\Application->doRun(???, ???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/src/Console/Application.php:77
   20.3813   44460312   6. Rector\Core\Console\Application->doRunCommand(???, ???, ???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/vendor/symfony/console/Application.php:235
   20.3813   44460312   7. Rector\Core\Console\Command\ProcessCommand->run(???, ???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/vendor/symfony/console/Application.php:849
   20.3814   44460312   8. Rector\Core\Console\Command\ProcessCommand->run(???, ???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/src/Console/Command/AbstractCommand.php:30
   20.3829   44463136   9. Rector\Core\Console\Command\ProcessCommand->execute(???, ???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/vendor/symfony/console/Command/Command.php:228
   20.4588   54583328  10. Rector\Core\Application\RectorApplication->runOnFileInfos(???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/src/Console/Command/ProcessCommand.php:147
  261.1745  127947576  11. Rector\Core\Application\RectorApplication->tryCatchWrapper(???, ???, ???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/src/Application/RectorApplication.php:119
  261.1755  127947576  12. Rector\Core\Application\RectorApplication->Rector\Core\Application\{closure:phar:///var/www/html/vendor/rector/rector-prefixed/rector/src/Application/RectorApplication.php:117-119}(???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/src/Application/RectorApplication.php:168
  261.1756  127947576  13. Rector\Core\Application\FileProcessor->refactor(???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/src/Application/RectorApplication.php:118
  261.1757  127947576  14. Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/src/Application/FileProcessor.php:107
  261.1757  127947576  15. Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php:58
  261.1760  127947576  16. Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverseArray(???) phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:85
  261.1772  127948000  17. Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverseNode(???) phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
  261.1786  127948000  18. Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverseArray(???) phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
  261.1798  127948424  19. Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverseNode(???) phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
  261.1830  127948424  20. Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverseArray(???) phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
  261.1842  127948848  21. Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverseNode(???) phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
  261.1917  127948848  22. Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverseArray(???) phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:105
  261.2073  127949320  23. Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverseNode(???) phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:196
  261.2081  127949320  24. DrupalRector\Rector\Deprecation\EntityManagerRector->enterNode(???) phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:113
  261.2082  127949432  25. DrupalRector\Rector\Deprecation\EntityManagerRector->refactor(???) phar:///var/www/html/vendor/rector/rector-prefixed/rector/src/Rector/AbstractRector.php:111
```

Can you please help me with this one?

**Comment by damontgomery** [comment] 2020-05-22 15:33
Thanks. Can you try with the latest version of this project using the `master` branch? I just merged in https://github.com/palantirnet/drupal-rector/pull/93 to refactor that rule to use the matching logic we learned as we build new rules.

The string casting was an old method and may be the cause of the issue you saw.

**Comment by jurgenhaas** [comment] 2020-05-22 16:36
@damontgomery looking good, my special use-case is now just fine with the master branch. Thanks a lot for the fix.

**Comment by damontgomery** [comment] 2020-05-22 16:53
Glad it works!

**Closed as completed by damontgomery** 2020-05-22 16:53 UTC
