### ISSUE TITLE
PHP Fatal error:  Class Rector\BetterPhpDocParser\PhpDocNode\Symfony\Validator\Constraints\AssertChoiceTagValueNode contains 1 abstract method and must therefore be declared abstract or implement the remaining methods

### ISSUE THREAD

**Issue by djdevin** [palantirnet/drupal-rector#140] opened 2021-04-20 14:18 UTC
After running through steps on https://github.com/palantirnet/drupal-rector and running rector against a Drupal module:

e.g. `vendor/bin/rector process web/modules/custom/quiz`

```
PHP Fatal error:  Class Rector\BetterPhpDocParser\PhpDocNode\Symfony\Validator\Constraints\AssertChoiceTagValueNode contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PHPStan\PhpDocParser\Ast\Node::hasAttribute) in [..]/vendor/rector/rector-prefixed/rector/packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php on line 13
Fatal error: Class Rector\BetterPhpDocParser\PhpDocNode\Symfony\Validator\Constraints\AssertChoiceTagValueNode contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PHPStan\PhpDocParser\Ast\Node::hasAttribute) in [..]/vendor/rector/rector-prefixed/rector/packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php on line 13
```

```
palantirnet/drupal-rector                                 0.5.6           Instant fixes for your Drupal code by using Rector.
rector/rector-prefixed                                    v0.7.29         Prefixed version of Rector compiled in PHAR
phpstan/phpstan                                           0.12.84         PHPStan - PHP Static Analysis Tool

PHP 7.4.16
```

**Comment by djdevin** [comment] 2021-04-20 15:54
This appears with phpstan/phpstan >= 0.12.82

Locking to 0.12.81 works.

**Comment by UltraBob** [comment] 2021-04-26 02:26
Thanks!  I ran into the same issue, and confirmed downgrading the phpstan version allows it to proceed.

**Comment by Judapriest** [comment] 2021-05-14 15:03
Locking to phpstan to 0.12.81 work as a quickfix.

The overall resolution seems to be link to https://github.com/palantirnet/drupal-rector/pull/144
By using this branch, locking phpstan is not needed.

**Comment by agentrickard** [comment] 2021-06-16 17:52
Closing, now that #144 is committed.

We also have https://www.drupal.org/project/rector/issues/3219160 as an issue.

**Closed as completed by agentrickard** 2021-06-16 17:52 UTC
